apiVersion: v1
kind: Namespace
metadata:
  name: user
  labels:
   name: user
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deployment
  namespace: user
  labels:
    app: user
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: blueapp/user:0.0.2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: user
  labels:
    app: user
spec:
  type: ClusterIP
  ports:
  - port: 1295
    targetPort: 8080
  selector:
    app: user
  externalName: user
